name: system-tool
version: '1.0.0'
summary: View the system information
description: |
  System information viewing tool with Qt5, divided into DBUS background
  and GUI front.

  Features currently included:
   * Detecting and displaying general system information

grade: stable
confinement: strict

#plugs:
#slots:
  # Depending on in which environment we're running we either need
  # to use the system or session DBus so we also need to have one
  # slot for each.
#  dbus-session:
#    interface: dbus
#    bus: session
#    name: org.freedesktop.systemtool
#    service: true
#  dbus-system:
#    interface: dbus
#    bus: system
#    name: org.freedesktop.systemtool
#    service: true

apps:
  system-tool:
    command: desktop-launch system-tool
    plugs: [home, unity7, desktop, desktop-legacy, x11, network, network-bind]
#    slots: [dbus-system]
#    slots:
#      - dbus-system
#      - dbus-session

#  system-tool-daemon:
#    command: bin/system-tool-daemon
#    plugs: [home, unity7, desktop, desktop-legacy, x11, network, network-bind]
#    slots:
#      - dbus-system
#      - dbus-session

parts:
  system-tool:
    plugin: qmake
    source: .
    qt-version: qt5
    project-files: [system-tool.pro]
    build-packages:
      - g++
      - qtbase5-dev
      - qt5-qmake
      - qtscript5-dev
      - qttools5-dev-tools
      - libgtop2-dev
      - pkg-config
    stage-packages:
      - libqt5core5a
      - libqt5dbus5
      - libqt5gui5
      - libqt5widgets5
      - libstdc++6
      - dmidecode
      - libgtop-2.0-10
    after: [desktop-qt5]
